name: Deploy IARANN to GitHub Pages

on:
  push:
    branches:
      - main # Asegúrate de que este sea el nombre de tu rama principal

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject API Key
        run: |
          # Reemplaza el marcador en el HTML por el secreto guardado en GitHub
          sed -i "s/__API_KEY_PLACEHOLDER__/${{ secrets.LASTFM_API_KEY }}/g" lastfm_collage.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
